name: CI
on:
  pull_request:
    branches: [ "main", "develop", "release" ]
  push: 
     branches: [ "main", "develop", "release" ]
jobs:
  ejecutar_pruebas:
    name: ejecutar pruebas del proyecto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: instalar depedencias
        run: flutter pub get
        working-directory: ./
      - name: Analiza el código 
        run: flutter analyze
        working-directory: ./
      - name: Ejecutar pruebas 
        run: flutter test
        working-directory: ./
  construir_ios:
    name: Build Flutter (IOS)
    needs: [ejecutar_pruebas]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: actions/flutter-action@v1
        with:
          channel: "stable"
      - name: instalar depedencias
        run: flutter pub get
        working-directory: ./
      - name: Limpiar proyecto
        run: flutter clean
        working-directory: ./
      - name: Construir aplicación
        run: flutter build ios --release --no-codesing
        working-directory: ./
  construir_appbundle:
    name: Build Flutter (Android)
    needs: [ejecutar_pruebas]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: instalar depedencias
        run: flutter pub get
        working-directory: ./
      - name: Construir aplicación 🚀
        run: flutter build appbundle
        working-directory: app_devops/
